name: Deploy PHP React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install React
        run: |
          cd fe-react
          npm install

      - name: Build React
        run: |
          cd fe-react
          npm run build

      - name: Check PHP
        run: |
          php -v
          find be-php -name "*.php" -print

      - name: Deploy placeholder
        run: echo "Deploy sau"
